modLoader="javafml"
loaderVersion="[36,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://github.com/VidTuGit/In-Game-Account-Switcher/issues"
[[mods]]
modId="ias"
version="7.1.0-pre1"
displayName="In-Game Account Switcher"
updateJSONURL="https://raw.githubusercontent.com/VidTuGit/In-Game-Account-Switcher/main/updater-forge.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher"
logoFile="iaslogo.png"
credits="deFENCE_(aka MRebhan), Elvm"
authors="The_Fireplace, The_BrainStone, VidTu"
description='''
Allows you to change which account you are signed in to in-game without restarting Minecraft.
'''