name: Bug Report
description: Report a bug or a crash
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: describe
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "The game crashes when I..."
    validations:
      required: true
  - type: textarea
    id: howtoreproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Launch the game.
        2. Click ???.
        3. Open ???.
        4. The game crashes.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: "Minecraft Version"
      description: |
        What version of Minecraft are you using?
        **Only versions listed here are supported.**
      options:
        - Fabric 1.17.1
        - Fabric 1.16.5
        - Fabric 1.15.2
        - Fabric 1.14.4
        - Forge 1.17.1
        - Forge 1.16.5
        - Forge 1.15.2
        - Forge 1.14.4
        - Forge 1.12.2
        - Forge 1.8.9
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: "Logs/Screenshots/Videos"
      description: "Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named 'latest.log', and can be found in the 'logs' folder. If you have one of these, please paste it to [Github Gist](https://gist.github.com/) or [Ubuntu Pastebin](https://paste.ubuntu.com/) and provide the link here. Do **not** attach the log file directly."
      placeholder: "https://gist.github.com/...."
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: 'Checklist'
      description: 'Check yourself before sending this issue.'
      options:
        - label: "I'm using the latest [mod version](https://modrinth.com/mod/in-game-account-switcher)"
          required: true
        - label: "I'm using the latest [Forge](https://files.minecraftforge.net) or [Fabric](https://fabricmc.net/use/)/[Fabric-API](https://modrinth.com/mod/fabric-api) for my Minecraft version"
          required: true
